#pragma once
#include <d3d9.h>
#include <d3dx9.h>
#include <dinput.h>
#include <cassert>
#include <cstdlib>
#include <time.h>
#include <string>
#include <sstream>
#include <fstream>
#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <hash_map>
#include <algorithm>
#include <memory.h>
#define NOMINMAX
#include <windows.h>
#undef min
#undef max